# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'dummyYummy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for dummyYummy

  pod 'SwiftLint'

  target 'dummyYummyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'dummyYummyUITests' do
    # Pods for testing
  end

  target 'dummyYummySnapshotTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'SnapshotTesting', '~> 1.9.0'
  end

end
